export const ENV_CREATE_REQUEST = 'ENV_CREATE_REQUEST'
export const ENV_CREATE_SUCCESS = 'ENV_CREATE_SUCCESS'
export const ENV_CREATE_FAIL = 'ENV_CREATE_FAIL'
export const ENV_CREATE_RESET = 'ENV_CREATE_RESET'

export const ENV_OPEN_REQUEST = 'ENV_OPEN_REQUEST'
export const ENV_OPEN_SUCCESS = 'ENV_OPEN_SUCCESS'
export const ENV_OPEN_FAIL = 'ENV_OPEN_FAIL'
export const ENV_OPEN_RESET = 'ENV_OPEN_RESET'

export const ENV_UPDATE_REQUEST = 'ENV_UPDATE_REQUEST'
export const ENV_UPDATE_SUCCESS = 'ENV_UPDATE_SUCCESS'
export const ENV_UPDATE_FAIL = 'ENV_UPDATE_FAIL'
export const ENV_UPDATE_RESET = 'ENV_UPDATE_RESET'

export const ENV_DELETE_REQUEST = 'ENV_DELETE_REQUEST'
export const ENV_DELETE_SUCCESS = 'ENV_DELETE_SUCCESS'
export const ENV_DELETE_FAIL = 'ENV_DELETE_FAIL'
export const ENV_DELETE_RESET = 'ENV_DELETE_RESET'
