export const WORKSPACE_ACTIVE_REQUEST = 'WORKSPACE_ACTIVE_REQUEST'
export const WORKSPACE_ACTIVE_SUCCESS = 'WORKSPACE_ACTIVE_SUCCESS'
export const WORKSPACE_ACTIVE_FAIL = 'WORKSPACE_ACTIVE_FAIL'
export const WORKSPACE_ACTIVE_RESET = 'WORKSPACE_ACTIVE_RESET'

export const WORKSPACE_UPDATE_REQUEST = 'WORKSPACE_UPDATE_REQUEST'
export const WORKSPACE_UPDATE_SUCCESS = 'WORKSPACE_UPDATE_SUCCESS'
export const WORKSPACE_UPDATE_FAIL = 'WORKSPACE_UPDATE_FAIL'
export const WORKSPACE_UPDATE_RESET = 'WORKSPACE_UPDATE_RESET'

export const WORKSPACE_ALL_REQUEST = 'WORKSPACE_ALL_REQUEST'
export const WORKSPACE_ALL_SUCCESS = 'WORKSPACE_ALL_SUCCESS'
export const WORKSPACE_ALL_FAIL = 'WORKSPACE_ALL_FAIL'
export const WORKSPACE_ALL_RESET = 'WORKSPACE_ALL_RESET'
