export const WORKSPACE_ACTIVE_REQUEST = "WORKSPACE_ACTIVE_REQUEST"
export const WORKSPACE_ACTIVE_SUCCESS = "WORKSPACE_ACTIVE_SUCCESS"
export const WORKSPACE_ACTIVE_FAIL = "WORKSPACE_ACTIVE_FAIL"
export const WORKSPACE_ACTIVE_RESET = "WORKSPACE_ACTIVE_RESET"

export const WORKSPACE_ALL_REQUEST = "WORKSPACE_ALL_REQUEST"
export const WORKSPACE_ALL_SUCCESS = "WORKSPACE_ALL_SUCCESS"
export const WORKSPACE_ALL_FAIL = "WORKSPACE_ALL_FAIL"
export const WORKSPACE_ALL_RESET = "WORKSPACE_ALL_RESET"

export const WORKSPACE_OPEN_REQ_REQUEST = "WORKSPACE_OPEN_REQ_REQUEST"
export const WORKSPACE_OPEN_REQ_SUCCESS = "WORKSPACE_OPEN_REQ_SUCCESS"
export const WORKSPACE_OPEN_REQ_FAIL = "WORKSPACE_OPEN_REQ_FAIL"
export const WORKSPACE_OPEN_REQ_RESET = "WORKSPACE_OPEN_REQ_RESET"
